options:
  any_auth: false
  human_patterns: true
services:
  '22':
    enabled: true
    type: ssh
  '23':
    enabled: true
    type: telnet
system:
  hostname: whatif
  os_template: CentOS
  password: admin1
  username: ze
