version: '1.0'
name: 'MIMIC Honeypot'
system:
  username: 'admin'
  password: 'admin123'
  hostname: 'dev-server'
  os_template: 'Ubuntu'
options:
  any_auth: true
  human_patterns: true
  enable_logging: true
  log_retention_days: 7
security:
  enabled: true
  rate_limits:
    max_connections_per_minute: 60
    max_failed_logins: 10
    block_duration_minutes: 60
    window_seconds: 60
  ip_blocking:
    auto_block_failed_logins: 10
services:
  22:
    type: 'ssh'
    enabled: true
    banner: 'SSH-2.0-OpenSSH_7.6p1'
    command_timeout: 30
    max_session_time: 3600
behavior:
  response_delay:
    min: 0.1
    max: 1.0
  error_rate: 0.05